from ..module import Mod, register
from .. import device

JUNK_DIRS = [".Spotlight-V100", "System Volume Information", ".Trashes", ".fseventsd", ".TemporaryItems"]


@register
class ContentsCleaner(Mod):
    id = "contents_cleaner"
    name = "Clean /contents Junk"
    category = "QOL"
    description = ("Remove the macOS/Windows metadata junk your computer writes into /contents when you "
                   "mount it (.Spotlight-V100, System Volume Information, .Trashes, ._* AppleDouble, "
                   ".DS_Store). Declutters + trims what the media scanner has to crawl. Does NOT touch "
                   "your music. (No revert — this junk is regenerated by your computer, not by you.)")
    status = "built"
    risk = "low"

    def preview(self, config, ctx):
        dq = device.shell('busybox find /contents -name "._*" 2>/dev/null | busybox wc -l').strip()
        ds = device.shell('busybox find /contents -name ".DS_Store" 2>/dev/null | busybox wc -l').strip()
        present = [d for d in JUNK_DIRS
                   if device.shell(f'[ -e "/contents/{d}" ] && echo y').strip() == "y"]
        return {"kind": "text", "data": (f"AppleDouble ._* files: {dq}\n.DS_Store files: {ds}\n"
                                         f"junk dirs present: {', '.join(present) or 'none'}")}

    def apply(self, config, ctx):
        device.shell('busybox find /contents -name "._*" -delete 2>/dev/null; '
                     'busybox find /contents -name ".DS_Store" -delete 2>/dev/null; true')
        for d in JUNK_DIRS:
            device.shell(f'busybox rm -rf "/contents/{d}" 2>/dev/null; true')
        return "cleaned macOS/Windows junk from /contents"

    def revert(self, ctx):
        return  # regenerated by the host OS; nothing to restore
